logging:
  level: 
    '[org.hibernate.stat]': debug

spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://10.22.1.60:5432/frequencia
    username: alverad
    password: 0279
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      '[hibernate.format_sql]' : true
      '[hibernate.generate_statistics]' : true