logging:
  level: 
    '[org.hibernate.stat]': debug

spring:
  devtools:
    add-properties: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
  
      '[hibernate.format_sql]' : true
      '[hibernate.generate_statistics]' : true